### ISSUE TITLE
TabBar and Toggle can be made simpler

### ISSUE THREAD

**Issue by heyarne** [rbb-data/starter#21]
1. Both components suffer from a weird effect that if you supply complex options, the callback gets called with `"[object Object]"`. This is because the value is serialized and JS serialization is bad. I have code that solves this by calling the callback with the according index and it works quite well.
2. They can be made more similar and thereby more predictable; you could for example call both callbacks `onChange` to be in line with standard DOM callbacks. Same applies for other props.

**Comment by errnesto** [comment]
I changeed it here: #23
could you review it please :-)
