### ISSUE TITLE
Color-Calculation for Diverging scales

### ISSUE THREAD

**Issue by HalukaMB** [rbb-data/starter#40]
The calculator for colours does not make colours for 3 categories when I type in 3. But 3+3+1 because 3 for each colour. Also: colours are not separated with commas as up there. And there is a type "datwarpper"

**Comment by errnesto** [comment]
What do you suggest?

For diverging scales I need an uneven number of steps so the generated scale contains the 0 value.
The easiest way to do this is to just double the count…

What would you expect to happen if you type in e.g 2 or 4?

**Comment by HalukaMB** [comment]
I would expect to generate a scale without the zero value. Like this https://nzzdev.github.io/Storytelling-Styleguide/#/colors?a=qualitative-color-scale-primary

Because there are cases when even a slight difference is important and there is no possibility of a zero (think of Dems/Reps in the US electorate system)
