### ISSUE TITLE
Header and subheader for all interactives

### ISSUE THREAD

**Issue by HalukaMB** [rbb-data/starter#41]
I love the swarmplot. However, what is missing is a header and subheader for the graphic – like we have in all Datawrapper graphics. Can we make this a mandatory element in every interactive app? https://www.rbb24.de/wirtschaft/thema/2020/coronavirus/beitraege_neu/2020/10/airbnb-wohnungen-vermietungen-anstieg-corona-berlin.html

**Comment by errnesto** [comment]
I'll create a Title component add it in the starter.

I think this should just look like a normal paragraph header:

![Bildschirmfoto 2020-10-29 um 17 39 13](https://user-images.githubusercontent.com/3065968/97604662-08891d00-1a0e-11eb-971f-3562f3eda164.png)

Then the content would do the same as a paragraph header does: Say wat you can read / see below.
The subtitle then could explain how to read the graph.

Below it comes the legend…

Also I think we should ask datawrapper to make the headeings smaller. The huge headings of the charts really break the hierarchy and visual flow:

![Bildschirmfoto 2020-10-29 um 17 47 24](https://user-images.githubusercontent.com/3065968/97605468-f2c82780-1a0e-11eb-8a40-a1eb5e48ca36.png)

**Comment by HalukaMB** [comment]
Wie definieren wir im Styleguide: Header und Subheader

Header: Ein Aussagesatz oder notfalls eine Kurzbeschreibung, wenn das eine Livegrafik ist
Also: "Wegen des guten Wetters ziehen Schwaben nach Berlin" oder "So viele Autos nutzt der Berliner Senat in diesem Jahr"
Nicht: "Wieder geht es bergab" oder "Zahl der Abgeordneten je Partei"

Subheader: Angabe der Metrik
Also: "Fernsehkonsum in Stunden pro Woche" oder "Krankenhausbetten je Region"
Nicht: "Wertschöpfung pro Jahr"(ohne Angabe der Einheit) oder "Das zeigt die Abhängigkeit von GEZ-Geldern"
