### ISSUE TITLE
Problems with Search / SearchInput stories

### ISSUE THREAD

**Issue by heyarne** [rbb-data/starter#5]
Looking at the sotrybook I noticed some problems with the components mentioned above:

1. It is not really clear to me why there is a `Search` and a `SearchInput` component or what the difference is
2. ~~The LocationSearch example only lists `opencage` options. This should be deprecated if I'm correct? At least for rbb|24 it is.~~

Forget about 2.) please, I just can't read properly…

**Comment by errnesto** [comment]
For some reason storybook does not display the comment sting for SearchInput :-(
I also tried to make it more clear:

 SearchInput that can show a list of suggestions
 This component provides no logic
 it just renders the search string and the provided result list
 and provides event handlers for user actions

The Search story is a collection of hooks and examples how to use the search input
the docstring says:

This is a basic example of how to use the search SearchInput component component with Openrouteservice
you can use this as is – or as an example for creating your own search

**Comment by errnesto** [comment]
@heyarne would you say this is resolved by ebd1b53
