### ISSUE TITLE
404 on fetching example data for `MapExample.js` (at /map)

### ISSUE THREAD

**Issue by sophiamersmann** [rbb-data/starter#57]
The map example doesn't work out of the box as the URL that points to the example data in `public/` is incorrect.

Line in question:
https://github.com/rbb-data/starter/blob/43de8cfab4fc11c03bc73cf9fe2d1824bccb9879/src/components/MapExample/MapExample.js#L16

Fixed by changing `window.location` to `window.location.origin`

If this makes sense to you, I can update this accordingly - either by pushing to master/main or doing a pull request (let me know)

**Comment by heyarne** [comment]
Thanks for the fix! Can you open a pull request?
