### ISSUE TITLE
Maps not rendered in Edge (v17) on Windows 10

### ISSUE THREAD

**Issue by sophiamersmann** [rbb-data/starter#61]
This is an issue related to next.js and fixed by upgrading next to the latest version.
Can we do this or is there a reason not to?

**Comment by jengeb** [comment]
Thanks for investigating this! I would support upgrading to the latest version of next.

**Comment by sophiamersmann** [comment]
Apparently, there are no breaking changes between version 9 and 10: https://nextjs.org/docs/upgrading

**Comment by heyarne** [comment]
Closed with the merge of #64
